# Generated by Django 5.1.4 on 2024-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_itme_price_cart_item_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="mobile",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
